# Generated by Django 4.1.1 on 2022-11-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="iha_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iha_marka", models.TextField()),
                ("iha_model", models.TextField()),
                ("iha_agr", models.FloatField()),
                ("iha_kat", models.TextField()),
                ("iha_fiyat", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="register_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.TextField()),
                ("user_surname", models.TextField()),
                ("user_password", models.CharField(max_length=50)),
                ("user_email", models.EmailField(max_length=254)),
            ],
        ),
    ]
