# Generated by Django 4.1.1 on 2022-11-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iha_app", "0003_kira_info_iha_agr_kira_info_iha_fiyat_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="kira_info", name="iha_kac_gün",),
    ]
